### ISSUE TITLE
Please tag this repository for releases

### ISSUE THREAD

**Issue by jeking3** [D-Programming-Deimos/libevent#13]
Folks need stable releases for their CI builds.  Tags help with this.  This repository has never had a "release".

**Comment by s-ludwig** [comment]
I suggest taking the tags from https://github.com/s-ludwig/libevent/releases when doing this, so that the DUB registry can be pointed to the official repository in the future. I don't have push access to this repository, so I can't do this myself currently.

**Comment by schveiguy** [comment]
@s-ludwig is there a way to automate that, or at least a command I can run to do it?

**Comment by schveiguy** [comment]
Also, @WalterBright can you add @s-ludwig as a member here?

**Comment by s-ludwig** [comment]
I think the two repositories should have identical commit histories, so that pulling tags from my repository and pushing with `git push --tags` to the deimos one should work.

**Comment by s-ludwig** [comment]
It's just three in total, though, so it may even be faster to create them manually.

**Comment by schveiguy** [comment]
> pushing with `git push --tags` to the deimos one should work

done

> so it may even be faster to create them manually

The cognitive load of doing that would have been much more taxing 😄

**Comment by s-ludwig** [comment]
Hehe, I was about to write the same, you beat me to it by 11 seconds ;-) Going to update code.dlang.org now.
